services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: portfolio-risk-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8081
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: portfolio-risk-backend-dev
    ports:
      - "8081:8080"
      - "5005:5005"  # Debug port
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/tradedb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - portfolio-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: portfolio-risk-redis-dev
    ports:
      - "6379:6379"
    networks:
      - portfolio-network
    restart: unless-stopped

volumes:
  maven_cache:
    driver: local

networks:
  portfolio-network:
    driver: bridge 